 "use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { apiFetch } from "./api";
import { toast } from "./toaster";
import { useStore } from "./store-provider";
export function AuthForm({mode}:{mode:"login"|"register"}){const router=useRouter();const {refresh}=useStore();const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");const r=await apiFetch("/api/auth/"+mode,{method:"POST",body:JSON.stringify({name,email,password})});setBusy(false);if(!r.ok){setError(r.error);return;}await refresh();toast(mode==="login"?"Welcome back.":"Account created.");router.push("/account");};
 return <div className="container-shell py-16 md:py-24"><div className="mx-auto max-w-md"><div className="text-center"><div className="kicker">{mode==="login"?"Welcome back":"Create your account"}</div><h1 className="display-serif mt-2 text-4xl font-bold">{mode==="login"?"Sign in":"Join Maison&Market"}</h1><p className="mt-3 text-sm text-muted">{mode==="login"?"Access orders, saved addresses and your wishlist.":"Save your wishlist, track orders and checkout faster."}</p></div><form onSubmit={submit} className="panel mt-8 p-6 md:p-8">{mode==="register"&&<div><label className="label">Full name</label><input required value={name} onChange={e=>setName(e.target.value)} className="input"/></div>}<div className={mode==="register"?"mt-5":""}><label className="label">Email</label><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="input" autoComplete="email"/></div><div className="mt-5"><label className="label">Password</label><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="input" autoComplete={mode==="login"?"current-password":"new-password"}/></div>{error&&<div role="alert" className="mt-4 rounded-xl bg-[#faf0f0] p-3 text-sm text-[#8c2929]">{error}</div>}<button disabled={busy} className="btn btn-dark mt-6 w-full disabled:opacity-50">{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button><div className="mt-5 text-center text-sm text-muted">{mode==="login"?<>New here? <Link href="/register" className="font-semibold text-[#171717] underline">Create an account</Link></>:<>Already have an account? <Link href="/login" className="font-semibold text-[#171717] underline">Sign in</Link></>}</div></form></div></div>}
