 "use client";
import Link from "next/link";
import { ArrowRight, Leaf, ShieldCheck, Truck, Sparkles } from "lucide-react";
import { useEffect,useState } from "react";
import { apiFetch } from "./api";
import { ProductGrid } from "./product-grid";
import { ProductGridSkeleton } from "./skeletons";

export function HomeClient(){
 const [featured,setFeatured]=useState<any[]|null>(null);const [newest,setNewest]=useState<any[]|null>(null);const [cats,setCats]=useState<any[]>([]);
 useEffect(()=>{Promise.all([apiFetch<any>("/api/products?limit=4&sort=featured"),apiFetch<any>("/api/products?limit=4&sort=newest"),apiFetch<any[]>("/api/categories")]).then(([a,b,c])=>{if(a.ok)setFeatured(a.data.items);if(b.ok)setNewest(b.data.items);if(c.ok)setCats(c.data)})},[]);
 return <div>
  <section className="container-shell py-5 md:py-7"><div className="relative min-h-[560px] overflow-hidden rounded-[28px] bg-[#e9e4da]"><img src="https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1800&q=88" alt="Calm modern interior" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/55 via-black/15 to-transparent"/><div className="relative flex min-h-[560px] max-w-2xl items-end p-7 text-white sm:p-12 md:p-16"><div><div className="kicker !text-white/80">The everyday, elevated</div><h1 className="display-serif mt-4 max-w-xl text-5xl font-bold leading-[.98] sm:text-6xl">Better things for slower living.</h1><p className="mt-5 max-w-lg text-base leading-7 text-white/85">A curated collection of useful objects, wearable essentials and small upgrades that make daily life feel more intentional.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/shop" className="btn bg-white text-[#171717]">Shop the collection <ArrowRight size={17}/></Link><Link href="#story" className="btn border border-white/40 bg-white/10 text-white backdrop-blur">Our point of view</Link></div></div></div></div></section>
  <section className="container-shell py-16 md:py-20"><div className="flex items-end justify-between gap-4"><div><div className="kicker">Start here</div><h2 className="display-serif mt-2 text-3xl font-bold md:text-4xl">Shop by category</h2></div><Link href="/shop" className="hidden text-sm font-semibold sm:inline-flex items-center gap-2">All products <ArrowRight size={15}/></Link></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">{cats.length?cats.slice(0,4).map((c,i)=><Link key={c.id} href={`/shop?category=${c.slug}`} className="group relative min-h-52 overflow-hidden rounded-[20px] bg-[#e4e0d8] p-5">{<img src={["https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=700&q=80","https://images.unsplash.com/photo-1512316609839-ce289d3eba0a?auto=format&fit=crop&w=700&q=80"][i]} alt="" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105"/>}<div className="absolute inset-0 bg-black/25"/><div className="relative flex h-full items-end"><div className="text-xl font-semibold text-white">{c.name}</div><ArrowRight size={18} className="ml-auto text-white"/></div></Link>):Array.from({length:4},(_,i)=><div key={i} className="skeleton min-h-52 rounded-[20px]"/>)}</div></section>
  <section className="container-shell py-8 md:py-12"><div className="flex items-end justify-between gap-4"><div><div className="kicker">Selected by us</div><h2 className="display-serif mt-2 text-3xl font-bold md:text-4xl">Featured pieces</h2></div><Link href="/shop?featured=true" className="text-sm font-semibold inline-flex items-center gap-2">View all <ArrowRight size={15}/></Link></div><div className="mt-8">{featured?<ProductGrid items={featured}/>:<ProductGridSkeleton/>}</div></section>
  <section id="story" className="container-shell py-20"><div className="grid items-center gap-10 md:grid-cols-[1.1fr_.9fr]"><div><div className="kicker">Our point of view</div><h2 className="display-serif mt-3 text-4xl font-bold leading-tight md:text-5xl">Less noise. More things you’ll actually keep.</h2><p className="mt-5 max-w-xl text-muted leading-7">We look for considered materials, useful proportions and quiet details. The goal is simple: products that work beautifully, feel good in the hand, and still make sense years from now.</p><Link href="/shop" className="btn btn-dark mt-7">Explore the edit</Link></div><div className="overflow-hidden rounded-[26px]"><img src="https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1100&q=86" alt="Curated objects at home" className="aspect-square w-full object-cover"/></div></div></section>
  <section className="bg-[#ece8df] py-16"><div className="container-shell"><div className="grid gap-8 md:grid-cols-4">{[[Leaf,"Considered materials","Built around longevity, not novelty."],[ShieldCheck,"Simple, secure checkout","Protected account and server-checked orders."],[Truck,"Thoughtful delivery","Free standard shipping over $150."],[Sparkles,"Human-sized service","Questions get a thoughtful answer."]].map(([Icon,title,body]:any)=><div key={title} className="border-t border-[#d4d0c6] pt-5"><Icon size={21}/><div className="mt-4 font-semibold">{title}</div><p className="mt-2 text-sm leading-6 text-muted">{body}</p></div>)}</div></div></section>
  <section className="container-shell py-20"><div className="flex items-end justify-between gap-4"><div><div className="kicker">Fresh perspective</div><h2 className="display-serif mt-2 text-3xl font-bold md:text-4xl">New arrivals</h2></div><Link href="/shop?sort=newest" className="text-sm font-semibold inline-flex items-center gap-2">See what’s new <ArrowRight size={15}/></Link></div><div className="mt-8">{newest?<ProductGrid items={newest}/>:<ProductGridSkeleton/>}</div></section>
  <section className="container-shell pb-20"><div className="rounded-[24px] bg-[#171717] px-6 py-12 text-center text-white md:px-12"><div className="kicker !text-white/60">Stay in the loop</div><h2 className="display-serif mt-3 text-4xl font-bold">A few good things, occasionally.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-white/70">New arrivals, useful edits and small seasonal notes. No noise.</p><div className="mx-auto mt-6 flex max-w-md gap-2"><input aria-label="Newsletter email" className="input bg-white/10 !border-white/20 !text-white placeholder:text-white/45" placeholder="you@example.com"/><button className="btn bg-white text-[#171717]">Subscribe</button></div></div></section>
 </div>
}