 "use client";
import { useEffect,useState } from "react";
import { SlidersHorizontal, X, ChevronDown } from "lucide-react";
import { ProductGrid } from "./product-grid";
import { ProductGridSkeleton } from "./skeletons";
import { apiFetch } from "./api";
import { useSearchParams,useRouter } from "next/navigation";

export function ShopClient(){
 const sp=useSearchParams();const router=useRouter();
 const [data,setData]=useState<any>(null); const page=Number(sp.get("page")||1); const tag=sp.get("tag")||"";const [cats,setCats]=useState<any[]>([]);const [drawer,setDrawer]=useState(false);const [sort,setSort]=useState(sp.get("sort")||"featured");const [category,setCategory]=useState(sp.get("category")||"");const [q,setQ]=useState(sp.get("q")||"");const [min,setMin]=useState("");const [max,setMax]=useState("");const [availability,setAvailability]=useState("");const [minRating,setMinRating]=useState("");
 const load=async()=>{setData(null);const params=new URLSearchParams({limit:"12",page:String(page),sort,...(q?{q}:{}),...(category?{category}:{}),...(tag?{tag}:{}),...(min?{min}:{}),...(max?{max}:{}),...(availability?{availability}:{}),...(minRating?{minRating}:{})});const r=await apiFetch<any>(`/api/products?${params}`);if(r.ok)setData(r.data)};
 useEffect(()=>{apiFetch<any[]>("/api/categories").then(r=>r.ok&&setCats(r.data))},[]);
 useEffect(()=>{load()},[sort,category,q,min,max,availability,minRating,page,tag]); 
 const update=(name:string,value:string)=>{const next=new URLSearchParams(sp.toString());value?next.set(name,value):next.delete(name);router.push(`/shop?${next.toString()}`)};
 return <div className="container-shell py-10 md:py-14"><div className="flex flex-col gap-5 border-b border-[var(--line)] pb-7 md:flex-row md:items-end md:justify-between"><div><div className="kicker">The collection</div><h1 className="display-serif mt-2 text-4xl font-bold md:text-5xl">Shop all</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted">Useful pieces across home, wear, accessories and travel.</p></div><div className="flex items-center gap-2"><button onClick={()=>setDrawer(true)} className="btn btn-secondary md:hidden"><SlidersHorizontal size={17}/> Filters</button><label className="relative"><span className="sr-only">Sort</span><select value={sort} onChange={e=>{setSort(e.target.value);update("sort",e.target.value)}} className="input !w-auto !min-h-[44px] pr-9"><option value="featured">Featured</option><option value="newest">Newest</option><option value="priceAsc">Price: low to high</option><option value="priceDesc">Price: high to low</option><option value="rating">Top rated</option></select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2"/></label></div></div>
 <div className="grid gap-8 py-8 md:grid-cols-[220px_1fr]"><aside className="hidden md:block"><Filters {...{cats,category,setCategory:(v:string)=>{setCategory(v);update("category",v)},q,setQ:(v:string)=>{setQ(v);update("q",v)},min,setMin,max,setMax,availability,setAvailability,minRating,setMinRating}}/></aside><div><div className="mb-5 flex items-center justify-between text-sm text-muted"><span>{data?`${data.total} products`:"Loading collection"}</span>{(q||category||min||max||availability||minRating||tag)&&<button onClick={()=>{setQ("");setCategory("");setMin("");setMax("");setAvailability("");setMinRating("");router.push("/shop")}} className="underline">Clear filters</button>}</div>{data?<ProductGrid items={data.items}/>:<ProductGridSkeleton/>}{data?.total===0&&<div className="panel mt-5 p-10 text-center"><div className="display-serif text-2xl font-bold">Nothing matched that edit.</div><p className="mt-2 text-sm text-muted">Try a wider search or remove a filter.</p></div>}{data&&data.pages>1&&<div className="mt-10 flex justify-center gap-2">{Array.from({length:data.pages},(_,i)=><button key={i} onClick={()=>{const next=new URLSearchParams(sp.toString());next.set("page",String(i+1));router.push(`/shop?${next.toString()}`);}} className={`grid h-10 w-10 place-items-center rounded-full border ${Number(sp.get("page")||1)===i+1?"bg-[#171717] text-white border-[#171717]":"bg-white border-[var(--line)]"}`}>{i+1}</button>)}</div>}</div></div>
 {drawer&&<div className="fixed inset-0 z-[80] bg-black/25 md:hidden" onClick={()=>setDrawer(false)}><div onClick={e=>e.stopPropagation()} className="h-full w-[min(360px,90vw)] bg-[var(--paper)] p-5"><div className="flex items-center justify-between"><div className="display-serif text-2xl font-bold">Filters</div><button onClick={()=>setDrawer(false)}><X/></button></div><div className="mt-7"><Filters {...{cats,category,setCategory:(v:string)=>{setCategory(v);update("category",v)},q,setQ:(v:string)=>{setQ(v);update("q",v)},min,setMin,max,setMax,availability,setAvailability,minRating,setMinRating}}/></div></div></div>}
 </div>
}
function Filters({cats,category,setCategory,q,setQ,min,setMin,max,setMax,availability,setAvailability,minRating,setMinRating}:any){return <div className="space-y-7"><div><div className="label">Search</div><input value={q} onChange={e=>setQ(e.target.value)} className="input" placeholder="Search products"/></div><div><div className="label">Category</div><div className="space-y-2">{[{name:"All",slug:""},...cats].map((c:any)=><button type="button" key={c.slug||"all"} onClick={()=>setCategory(c.slug)} className={`block w-full rounded-xl px-3 py-2 text-left text-sm ${category===c.slug?"bg-white font-semibold":"text-muted hover:bg-white"}`}>{c.name}</button>)}</div></div><div><div className="label">Price</div><div className="grid grid-cols-2 gap-2"><input value={min} onChange={e=>setMin(e.target.value)} className="input" type="number" placeholder="Min"/><input value={max} onChange={e=>setMax(e.target.value)} className="input" type="number" placeholder="Max"/></div></div><div><div className="label">Rating</div><select className="input" value={minRating} onChange={e=>setMinRating(e.target.value)}><option value="">Any rating</option><option value="4">4+ stars</option><option value="3">3+ stars</option></select></div><div><div className="label">Availability</div><label className="flex items-center gap-2 text-sm"><input checked={availability==="in-stock"} onChange={e=>setAvailability(e.target.checked?"in-stock":"")} type="checkbox"/> In stock only</label></div></div>}
